<?php
/**
 * Asset management helper.
 *
 * @package SampleHQForm\Helpers
 */

declare( strict_types=1 );

namespace SampleHQForm\Helpers;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Handles script and style registration and enqueueing.
 *
 * Uses .asset.php files generated by @wordpress/scripts for dependencies.
 */
class Assets {

	/**
	 * Register and enqueue an admin script built by @wordpress/scripts.
	 *
	 * Reads the .asset.php file for dependencies and version hash.
	 *
	 * @param string $handle Script handle (matches the build output filename without extension).
	 * @return void
	 */
	public static function enqueue_admin_script( string $handle ): void {
		$asset = self::get_asset_data( $handle );

		wp_enqueue_script(
			'shqf-' . $handle,
			SHQF_URL . 'assets/build/' . $handle . '.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		wp_set_script_translations( 'shqf-' . $handle, 'samplehq-request-form' );
	}

	/**
	 * Register and enqueue an admin stylesheet.
	 *
	 * @param string $handle  Style handle.
	 * @param string $subpath Path relative to assets/build/ (e.g., 'form-builder.css').
	 * @return void
	 */
	public static function enqueue_admin_style( string $handle, string $subpath = '' ): void {
		$path = ! empty( $subpath ) ? $subpath : $handle . '.css';

		wp_enqueue_style(
			'shqf-' . $handle,
			SHQF_URL . 'assets/build/' . $path,
			[],
			SHQF_VERSION
		);
	}

	/**
	 * Register and enqueue a public-facing script.
	 *
	 * Only enqueued when a form shortcode or block is present on the page.
	 *
	 * @param string $handle Script handle.
	 * @return void
	 */
	public static function enqueue_public_script( string $handle ): void {
		$asset = self::get_asset_data( $handle );

		wp_enqueue_script(
			'shqf-' . $handle,
			SHQF_URL . 'assets/build/' . $handle . '.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);
	}

	/**
	 * Register and enqueue a public-facing stylesheet.
	 *
	 * @param string $handle  Style handle.
	 * @param string $subpath Path relative to assets/build/.
	 * @return void
	 */
	public static function enqueue_public_style( string $handle, string $subpath = '' ): void {
		$path = ! empty( $subpath ) ? $subpath : $handle . '.css';

		wp_enqueue_style(
			'shqf-' . $handle,
			SHQF_URL . 'assets/build/' . $path,
			[],
			SHQF_VERSION
		);
	}

	/**
	 * Enqueue fonts (Space Grotesk + Inter) for public form rendering.
	 *
	 * Fonts are self-hosted (woff2 files bundled with the plugin) to comply
	 * with WordPress.org guidelines against external CDN resources.
	 *
	 * @return void
	 */
	public static function enqueue_google_fonts(): void {
		/**
		 * Filter whether to load the plugin's bundled fonts. Themes that
		 * already include Inter/Space Grotesk can disable this to avoid
		 * duplicate font loading.
		 *
		 * @param bool $load Whether to load fonts. Default true.
		 */
		if ( ! apply_filters( 'shqf_load_google_fonts', true ) ) {
			return;
		}

		wp_enqueue_style(
			'shqf-fonts',
			plugins_url( 'assets/fonts/fonts.css', SHQF_FILE ),
			[],
			SHQF_VERSION
		);
	}

	/**
	 * Enqueue the Cloudflare Turnstile script if configured.
	 *
	 * @return void
	 */
	public static function maybe_enqueue_turnstile(): void {
		$site_key = (string) get_option( 'shqf_turnstile_site_key', '' );
		if ( '' === $site_key ) {
			return;
		}

		// phpcs:ignore PluginCheck.CodeAnalysis.EnqueuedResourceOffloading.OffloadedContent -- Cloudflare Turnstile CAPTCHA must load from their CDN (third-party service requirement).
		wp_enqueue_script(
			'cf-turnstile',
			'https://challenges.cloudflare.com/turnstile/v0/api.js',
			[],
			null, // phpcs:ignore WordPress.WP.EnqueuedResourceParameters.MissingVersion
			true
		);
	}

	/**
	 * Read the .asset.php file generated by @wordpress/scripts.
	 *
	 * Falls back to plugin version and empty deps if the file doesn't exist.
	 *
	 * @param string $handle Build output handle (filename without extension).
	 * @return array{dependencies: string[], version: string}
	 */
	private static function get_asset_data( string $handle ): array {
		$asset_file = SHQF_DIR . 'assets/build/' . $handle . '.asset.php';

		if ( file_exists( $asset_file ) ) {
			$asset = require $asset_file;
			return [
				'dependencies' => $asset['dependencies'] ?? [],
				'version'      => $asset['version'] ?? SHQF_VERSION,
			];
		}

		return [
			'dependencies' => [],
			'version'      => SHQF_VERSION,
		];
	}
}
